runtime: nodejs20

env_variables:
  GOOGLE_CLOUD_PROJECT_ID: gen-ai-hackathon-472505
  # All other credentials set via Google Cloud Console or local .env only

automatic_scaling:
  min_instances: 0
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 1